apiVersion: eksctl.io/v1alpha5
availabilityZones:
- eu-central-1a
- eu-central-1b
cloudWatch:
  clusterLogging: {}
iam:
  vpcResourceControllerPolicy: true
  withOIDC: false
addons:
- name: eks-pod-identity-agent
- name: aws-ebs-csi-driver
  useDefaultPodIdentityAssociations: true
- name: vpc-cni
  useDefaultPodIdentityAssociations: true
  configurationValues: |
    {
      "env": {
        "ENABLE_PREFIX_DELEGATION": "true",
        "WARM_PREFIX_TARGET": "1"
      }
    }
kind: ClusterConfig
kubernetesNetworkConfig:
  ipFamily: IPv4
managedNodeGroups:
- amiFamily: Ubuntu2204
  iam:
    withAddonPolicies:
      ebs: true
  instanceType: t3.2xlarge
  maxSize: 2
  minSize: 2
  maxPodsPerNode: 110
  name: ng-d06bd84e
  releaseVersion: ""
  tags:
    alpha.eksctl.io/nodegroup-name: ng-d06bd84e
    alpha.eksctl.io/nodegroup-type: managed
  volumeSize: 100
metadata:
  name: kubeflow-test
  region: eu-central-1
  version: "1.33"
