# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist = True
envlist = test-deployment

[vars]
tests_path = {tox_root}/tests/

[testenv]
allowlist_externals =
    poetry
passenv =
    KUBECONFIG
    PYTHONPATH
setenv =
    # Needed for juju cli to work correctly
    HOME={env:HOME}

[testenv:lint]
description = Check Python code against coding style standards
commands =
    poetry install --only fmt,lint
    poetry run ruff check {[vars]tests_path}

[testenv:fmt]
description = Apply coding style standards to code
commands =
    poetry install --only fmt
    poetry run ruff format {[vars]tests_path}

[testenv:test-deployment]
description = Test bundle deployment
commands =
    poetry install --with integration
    poetry run pytest -v --tb native --asyncio-mode=auto {[vars]tests_path}test_deployment.py --log-cli-level=INFO -s {posargs}

[testenv:update-requirements]
description = Update requirements, including those in charm subfolders
commands = 
	poetry lock --regenerate
skip_install = true