# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
envlist = 
    lint-{auth,core,istio-ambient,istio-sidecar,feast,katib,kfp,kubeflow,kubeflow-cos,minio,mlflow,notebooks,observability,resource-dispatcher,tensorboard,training}
    validate-{auth,core,istio-ambient,istio-sidecar,feast,katib,kfp,kubeflow,kubeflow-cos,minio,mlflow,notebooks,observability,resource-dispatcher,tensorboard,training}

[vars]
tf_modules_path = {tox_root}/../terraform-refactoring/

[testenv]
allowlist_externals =
    /bin/bash
    terraform
    tflint
set_env =
    # set type (charms, components, products)
    auth: TYPE=components
    core: TYPE=components
    istio-ambient: TYPE=components
    istio-sidecar: TYPE=components
    feast: TYPE=components
    katib: TYPE=components
    kfp: TYPE=components
    kubeflow: TYPE=products
    kubeflow-cos: TYPE=deployments
    minio: TYPE=charms
    mlflow: TYPE=components
    notebooks: TYPE=components
    observability: TYPE=components
    resource-dispatcher: TYPE=charms
    tensorboard: TYPE=components
    training: TYPE=components
    # set module name
    auth: MODULE=auth
    core: MODULE=core
    istio-ambient: MODULE=istio-ambient
    istio-sidecar: MODULE=istio-sidecar
    feast: MODULE=feast
    katib: MODULE=katib
    kfp: MODULE=kfp
    kubeflow: MODULE=kubeflow
    kubeflow-cos: MODULE=kubeflow-cos
    minio: MODULE=minio
    mlflow: MODULE=mlflow
    notebooks: MODULE=notebooks
    observability: MODULE=observability
    resource-dispatcher: MODULE=resource-dispatcher
    tensorboard: MODULE=tensorboard
    training: MODULE=training

[testenv:lint-{auth,core,istio-ambient,istio-sidecar,feast,katib,kubeflow,kubeflow-cos,minio,mlflow,notebooks,observability,minio,mlflow,resource-dispatcher,tensorboard}]
description = Check Terraform code against coding style standards
commands =
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} fmt -recursive -check -diff
    tflint --recursive --chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE}

[testenv:validate-{auth,core,istio-ambient,istio-sidecar,feast,katib,kfp,kubeflow,kubeflow-cos,minio,mlflow,notebooks,observability,minio,mlflow,notebooks,resource-dispatcher,tensorboard,training}]
description = Apply coding style standards to code
commands =
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} init
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} validate -no-color

[testenv:fmt]
description = Apply coding style standards to code
commands =
    terraform -chdir={[vars]tf_modules_path} fmt -recursive
    tflint --recursive --fix --chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE}

[testenv:generate-docs]
description = Generate reference docs for terraform modules
commands =
    /bin/bash generate-docs.sh
