# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
envlist = 
    lint-{auth,core,istio-ambient,istio-sidecar,katib,kfp,kubeflow,minio}
    validate-{auth,core,istio-ambient,istio-sidecar,katib,kfp,kubeflow,minio}

[vars]
tf_modules_path = {tox_root}/../terraform-refactoring/

[testenv]
allowlist_externals =
    /bin/bash
    terraform
set_env =
    # set type (charms, components, products)
    auth: TYPE=components
    core: TYPE=components
    istio-ambient: TYPE=components
    istio-sidecar: TYPE=components
    katib: TYPE=components
    kfp: TYPE=components
    kubeflow: TYPE=products
    minio: TYPE=charms
    # set module name
    auth: MODULE=auth
    core: MODULE=core
    istio-ambient: MODULE=istio-ambient
    istio-sidecar: MODULE=istio-sidecar
    katib: MODULE=katib
    kfp: MODULE=kfp
    kubeflow: MODULE=kubeflow
    minio: MODULE=minio

[testenv:lint-{auth,core,istio-ambient,istio-sidecar,katib,kubeflow,minio}]
description = Check Terraform code against coding style standards
allowlist_externals =
    terraform
    tflint
commands =
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} fmt -recursive -check -diff
    tflint --recursive --chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE}

[testenv:validate-{auth,core,istio-ambient,istio-sidecar,katib,kfp,kubeflow,minio}]
description = Apply coding style standards to code
allowlist_externals =
    terraform
commands =
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} init
    terraform -chdir={[vars]tf_modules_path}{env:TYPE}/{env:MODULE} validate -no-color 

[testenv:fmt]
description = Apply coding style standards to code
allowlist_externals =
    terraform
commands =
   terraform -chdir={[vars]tf_modules_path} fmt -recursive

[testenv:generate-docs]
description = Generate reference docs for terraform modules
commands =
    /bin/bash generate-docs.sh
