# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
envlist = tflint

[testenv:tflint]
description = Check Terraform code against coding style standards
allowlist_externals =
    tflint
commands =
    tflint --recursive

[testenv:fmt]
description = Apply coding style standards to code
allowlist_externals =
    terraform
commands =
   terraform fmt
