name: Create K8s cluster, deploy kubeflow-mlflow Terraform solution and run UATs
on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Kubernetes version to be used for the AKS cluster. Make sure that the corresponding K8s version is supported by the cloud.'
        required: false
      uats_branch:
        description: 'Branch to run the UATs from e.g. main or track/1.10. By default, this is defined by the dependencies.yaml file.'
        required: false
  pull_request:
  schedule:
    - cron: "17 02 * * 1"

jobs:
  deploy-solution:
    name: Deploy CKF + MLFlow solution to K8s
    runs-on: ["self-hosted-linux-amd64-noble-xlarge"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set envvars from dependencies.yaml
        run: |
          yq eval 'to_entries | .[] | "\(.key)=\(.value)"' ".github/dependencies.yaml" | while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done

      - name: Update ENV variables from inputs if available
        run: |
          K8S_VERSION=${{ inputs.k8s_version || env.K8S_VERSION }}
          echo "K8S_VERSION=${K8S_VERSION}" >> $GITHUB_ENV
          UATS_BRANCH=${{ inputs.uats_branch || env.UATS_BRANCH }}
          echo "UATS_BRANCH=${UATS_BRANCH}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install tox & poetry
        run: |
          sudo apt-get install -yqq pipx
          pipx ensurepath
          sudo pipx ensurepath
          
          pipx install tox
          pipx install poetry

      - name: Setup environment
        run: |
          if [ -n "$DOCKERHUB_MIRROR" ]; then
          MIRROR_CONFIG=/opt/containerd/k8s-containerd/etc/containerd/hosts.d/docker.io
            
          sudo mkdir -p ${MIRROR_CONFIG}
          sudo chown $USER ${MIRROR_CONFIG}
          cat << EOF > ${MIRROR_CONFIG}/hosts.toml
          [host."$DOCKERHUB_MIRROR"]
          capabilities = ["pull", "resolve"]
          EOF
          fi
          
          sudo apt-get remove -y docker.io containerd
          sudo rm -rf /run/containerd
          sudo snap install concierge --classic
          cd .github
          sudo concierge prepare --trace
          cd ..

      - name: Setup terraform
        run: |          
          sudo snap install terraform  --channel latest/stable --classic
          terraform --version

      - name: Deploy and assert kubeflow-mlflow solution
        run: |
          juju switch concierge-k8s
          tox -c ./modules/kubeflow-mlflow -vve test_deployment -- -vv -s

      - name: Run UATs
        run: |
          git clone https://github.com/canonical/charmed-kubeflow-uats.git ~/charmed-kubeflow-uats
          cd ~/charmed-kubeflow-uats
          git checkout ${{ env.UATS_BRANCH }}
          tox -e uats-remote -- --filter "not feast"

      # On failure, capture debugging resources
      - name: Select model
        run: juju switch kubeflow
        if: failure() || cancelled()

      - name: Get juju status
        run: juju status
        if: failure() || cancelled()

      - name: Get juju debug logs
        run: juju debug-log --replay --no-tail
        if: failure() || cancelled()

      - name: Get all kubernetes resources
        run: kubectl get all -A
        if: failure() || cancelled()

      - name: Describe all pods
        if: failure() || cancelled()
        run: kubectl describe pods --all-namespaces

      - name: Get logs from pods with status = Pending
        run: kubectl -n kubeflow get pods | tail -n +2 | grep Pending | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
        if: failure() || cancelled()

      - name: Get logs from pods with status = Failed
        run: kubectl -n kubeflow get pods | tail -n +2 | grep Failed | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
        if: failure() || cancelled()

      - name: Get logs from pods with status = CrashLoopBackOff
        run: kubectl -n kubeflow get pods | tail -n +2 | grep CrashLoopBackOff | awk '{print $1}' | xargs -n1 kubectl -n kubeflow logs --all-containers=true --tail 100
        if: failure() || cancelled()
