name: Testing Action
on:
  workflow_dispatch:
    inputs:
      k8s_version:
        description: 'Kubernetes version to be used for the AKS cluster. Make sure that the corresponding K8s version is supported by the cloud.'
        required: false
      uats_branch:
        description: 'Branch to run the UATs from e.g. main or track/1.10. By default, this is defined by the dependencies.yaml file.'
        required: false
      ckf_version:
        description: 'Charmed Kubeflow version to be tested'
        required: false
      risk:
        description: 'The risk level to be tested'
        required: false
        default: 'stable'
  pull_request:
  schedule:
    - cron: "17 02 * * 1"

jobs:
  deploy-solution-to-aks:
    name: Deploy CKF + MLFlow solution to AKS
    runs-on: ubuntu-24.04
    env:
      AZURE_CORE_OUTPUT: none

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set envvars from dependencies.yaml
        run: |
          yq eval 'to_entries | .[] | "\(.key)=\(.value)"' ".github/dependencies.yaml" | while IFS= read -r line; do
            echo "$line" >> "$GITHUB_ENV"
          done

      - name: Update ENV variables from inputs if available
        run: |
          K8S_VERSION=${{ inputs.k8s_version || env.K8S_VERSION }}
          echo "K8S_VERSION=${K8S_VERSION}" >> $GITHUB_ENV
          CKF_VERSION=${{ inputs.ckf_version || env.CKF_VERSION }}
          echo "CKF_VERSION=${CKF_VERSION}" >> $GITHUB_ENV
          
          if [[ -z "${{ inputs.uats_branch }}" ]]; then UATS_BRANCH="track/${CKF_VERSION}"; else UATS_BRANCH=${{ inputs.uats_branch }}; fi
          echo "UATS_BRANCH=${UATS_BRANCH}" >> $GITHUB_ENV

      - name: Deploy and assert kubeflow-mlflow solution
        run: |
          if [[ '${{ github.event_name }}' != 'pull_request' ]]; then
            git checkout 'track/${{ env.CKF_VERSION }}'
          fi
          echo "Current commit: $(git rev-parse HEAD)"

      - name: Run UATs
        run: |
          git clone https://github.com/canonical/charmed-kubeflow-uats.git ~/charmed-kubeflow-uats
          cd ~/charmed-kubeflow-uats
          git checkout ${{ env.UATS_BRANCH }}
          echo "Current branch: $(git branch --show-current)"

