
# reusable workflow triggered by other actions
name: CI

on:
  pull_request:

  push:
    branches:
    - main
    - track/**

jobs:

  terraform-checks:
    name: Terraform
    uses: canonical/charmed-kubeflow-workflows/.github/workflows/terraform-checks-solution.yaml@kf-6347-ci-terraform-lint-format
    with:
      module-path: kubeflow
